version: '3.9'
services:
  adaptor:
    build: ./adaptor
    expose:
      - "80"
    depends_on:
      - catalog
    ports:
      - "8082:80"
    environment:
      CATALOG_HOST: catalog
      CATALOG_PORT: 80
      TZ: "Europe/Rome"
  catalog:
    build: ./catalog
    expose:
      - "80"
    ports:
      - "8080:80"
    environment:
      TZ: "Europe/Rome"
  control:
    build: ./control
    depends_on:
      - catalog
    environment:
      CATALOG_HOST: catalog
      CATALOG_PORT: 80
      TZ: "Europe/Rome"
  device:
    build: ./device
    depends_on:
      - catalog
    environment:
      CATALOG_HOST: catalog
      CATALOG_PORT: 80    
      TZ: "Europe/Rome"
  telegram:
    build: ./telegram
    expose:
      - "80"
    ports:
      - "8081:80"
    depends_on:
      - catalog
    environment:
      CATALOG_HOST: catalog
      CATALOG_PORT: 80
      TZ: "Europe/Rome"