FROM python:3.9-slim
#FROM python:3.9-alpine
COPY . .
RUN pip3 install -r requirements.txt
#CMD ["python3","./air_control.py","./time_control.py","./Data_analysis.py"]
CMD ["python3","./air_control.py"]